package abc.tzous4j.dims.model;

public class Tbdevinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer devid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.famsid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String famsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.eamid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String eamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devsn
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devbrand
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devbrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.siteid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer siteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.keeper
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String keeper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devlocation
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devlevel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.devstat
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.remarks
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.isasset
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String isasset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevinfo.opdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String opdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devid
     *
     * @return the value of tbdevinfo.devid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getDevid() {
        return devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devid
     *
     * @param devid the value for tbdevinfo.devid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevid(Integer devid) {
        this.devid = devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.famsid
     *
     * @return the value of tbdevinfo.famsid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getFamsid() {
        return famsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.famsid
     *
     * @param famsid the value for tbdevinfo.famsid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setFamsid(String famsid) {
        this.famsid = famsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.eamid
     *
     * @return the value of tbdevinfo.eamid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getEamid() {
        return eamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.eamid
     *
     * @param eamid the value for tbdevinfo.eamid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setEamid(String eamid) {
        this.eamid = eamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devsn
     *
     * @return the value of tbdevinfo.devsn
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevsn() {
        return devsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devsn
     *
     * @param devsn the value for tbdevinfo.devsn
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevsn(String devsn) {
        this.devsn = devsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devname
     *
     * @return the value of tbdevinfo.devname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevname() {
        return devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devname
     *
     * @param devname the value for tbdevinfo.devname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevname(String devname) {
        this.devname = devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devbrand
     *
     * @return the value of tbdevinfo.devbrand
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevbrand() {
        return devbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devbrand
     *
     * @param devbrand the value for tbdevinfo.devbrand
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevbrand(String devbrand) {
        this.devbrand = devbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devmodel
     *
     * @return the value of tbdevinfo.devmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevmodel() {
        return devmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devmodel
     *
     * @param devmodel the value for tbdevinfo.devmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevmodel(String devmodel) {
        this.devmodel = devmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devdate
     *
     * @return the value of tbdevinfo.devdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevdate() {
        return devdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devdate
     *
     * @param devdate the value for tbdevinfo.devdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevdate(String devdate) {
        this.devdate = devdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.siteid
     *
     * @return the value of tbdevinfo.siteid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.siteid
     *
     * @param siteid the value for tbdevinfo.siteid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.keeper
     *
     * @return the value of tbdevinfo.keeper
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getKeeper() {
        return keeper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.keeper
     *
     * @param keeper the value for tbdevinfo.keeper
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setKeeper(String keeper) {
        this.keeper = keeper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devlocation
     *
     * @return the value of tbdevinfo.devlocation
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevlocation() {
        return devlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devlocation
     *
     * @param devlocation the value for tbdevinfo.devlocation
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevlocation(String devlocation) {
        this.devlocation = devlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devlevel
     *
     * @return the value of tbdevinfo.devlevel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevlevel() {
        return devlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devlevel
     *
     * @param devlevel the value for tbdevinfo.devlevel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevlevel(String devlevel) {
        this.devlevel = devlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.devstat
     *
     * @return the value of tbdevinfo.devstat
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevstat() {
        return devstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.devstat
     *
     * @param devstat the value for tbdevinfo.devstat
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevstat(String devstat) {
        this.devstat = devstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.remarks
     *
     * @return the value of tbdevinfo.remarks
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.remarks
     *
     * @param remarks the value for tbdevinfo.remarks
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.isasset
     *
     * @return the value of tbdevinfo.isasset
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getIsasset() {
        return isasset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.isasset
     *
     * @param isasset the value for tbdevinfo.isasset
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setIsasset(String isasset) {
        this.isasset = isasset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevinfo.opdate
     *
     * @return the value of tbdevinfo.opdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getOpdate() {
        return opdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevinfo.opdate
     *
     * @param opdate the value for tbdevinfo.opdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setOpdate(String opdate) {
        this.opdate = opdate;
    }
}