package abc.tzous4j.dims.model;

public class Tbdevlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.logid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.oper
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String oper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.op
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String op;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.opdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String opdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.optime
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String optime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.devid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer devid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.okeys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String okeys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevlog.nkeys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String nkeys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.logid
     *
     * @return the value of tbdevlog.logid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.logid
     *
     * @param logid the value for tbdevlog.logid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.oper
     *
     * @return the value of tbdevlog.oper
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.oper
     *
     * @param oper the value for tbdevlog.oper
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setOper(String oper) {
        this.oper = oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.op
     *
     * @return the value of tbdevlog.op
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.op
     *
     * @param op the value for tbdevlog.op
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setOp(String op) {
        this.op = op;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.opdate
     *
     * @return the value of tbdevlog.opdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getOpdate() {
        return opdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.opdate
     *
     * @param opdate the value for tbdevlog.opdate
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setOpdate(String opdate) {
        this.opdate = opdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.optime
     *
     * @return the value of tbdevlog.optime
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getOptime() {
        return optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.optime
     *
     * @param optime the value for tbdevlog.optime
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setOptime(String optime) {
        this.optime = optime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.devid
     *
     * @return the value of tbdevlog.devid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getDevid() {
        return devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.devid
     *
     * @param devid the value for tbdevlog.devid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevid(Integer devid) {
        this.devid = devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.okeys
     *
     * @return the value of tbdevlog.okeys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getOkeys() {
        return okeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.okeys
     *
     * @param okeys the value for tbdevlog.okeys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setOkeys(String okeys) {
        this.okeys = okeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevlog.nkeys
     *
     * @return the value of tbdevlog.nkeys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getNkeys() {
        return nkeys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevlog.nkeys
     *
     * @param nkeys the value for tbdevlog.nkeys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setNkeys(String nkeys) {
        this.nkeys = nkeys;
    }
}