package abc.tzous4j.dims.model;

public class Tbdevtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevtype.typeid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevtype.typename
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevtype.superid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer superid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevtype.typeid
     *
     * @return the value of tbdevtype.typeid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevtype.typeid
     *
     * @param typeid the value for tbdevtype.typeid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevtype.typename
     *
     * @return the value of tbdevtype.typename
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevtype.typename
     *
     * @param typename the value for tbdevtype.typename
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevtype.superid
     *
     * @return the value of tbdevtype.superid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getSuperid() {
        return superid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevtype.superid
     *
     * @param superid the value for tbdevtype.superid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setSuperid(Integer superid) {
        this.superid = superid;
    }
}