package abc.tzous4j.dims.model;

public class Tbdevmodel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevmodel.modelid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer modelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevmodel.devbrand
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devbrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevmodel.devmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String devmodel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdevmodel.typeid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer typeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevmodel.modelid
     *
     * @return the value of tbdevmodel.modelid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevmodel.modelid
     *
     * @param modelid the value for tbdevmodel.modelid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setModelid(Integer modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevmodel.devbrand
     *
     * @return the value of tbdevmodel.devbrand
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevbrand() {
        return devbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevmodel.devbrand
     *
     * @param devbrand the value for tbdevmodel.devbrand
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevbrand(String devbrand) {
        this.devbrand = devbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevmodel.devmodel
     *
     * @return the value of tbdevmodel.devmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getDevmodel() {
        return devmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevmodel.devmodel
     *
     * @param devmodel the value for tbdevmodel.devmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setDevmodel(String devmodel) {
        this.devmodel = devmodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdevmodel.typeid
     *
     * @return the value of tbdevmodel.typeid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdevmodel.typeid
     *
     * @param typeid the value for tbdevmodel.typeid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }
}