package abc.tzous4j.dims.model;

public class Tbgrp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbgrp.gid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbgrp.gsite
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer gsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbgrp.gname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbgrp.ghid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer ghid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbgrp.gstat
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer gstat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbgrp.gid
     *
     * @return the value of tbgrp.gid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbgrp.gid
     *
     * @param gid the value for tbgrp.gid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbgrp.gsite
     *
     * @return the value of tbgrp.gsite
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getGsite() {
        return gsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbgrp.gsite
     *
     * @param gsite the value for tbgrp.gsite
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setGsite(Integer gsite) {
        this.gsite = gsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbgrp.gname
     *
     * @return the value of tbgrp.gname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbgrp.gname
     *
     * @param gname the value for tbgrp.gname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setGname(String gname) {
        this.gname = gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbgrp.ghid
     *
     * @return the value of tbgrp.ghid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getGhid() {
        return ghid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbgrp.ghid
     *
     * @param ghid the value for tbgrp.ghid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setGhid(Integer ghid) {
        this.ghid = ghid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbgrp.gstat
     *
     * @return the value of tbgrp.gstat
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getGstat() {
        return gstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbgrp.gstat
     *
     * @param gstat the value for tbgrp.gstat
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setGstat(Integer gstat) {
        this.gstat = gstat;
    }
}