package abc.tzous4j.dims.model;

public class Tbsys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsys.sysid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer sysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsys.sysname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String sysname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbsys.sysversion
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private String sysversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsys.sysid
     *
     * @return the value of tbsys.sysid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getSysid() {
        return sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsys.sysid
     *
     * @param sysid the value for tbsys.sysid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setSysid(Integer sysid) {
        this.sysid = sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsys.sysname
     *
     * @return the value of tbsys.sysname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getSysname() {
        return sysname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsys.sysname
     *
     * @param sysname the value for tbsys.sysname
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setSysname(String sysname) {
        this.sysname = sysname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbsys.sysversion
     *
     * @return the value of tbsys.sysversion
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public String getSysversion() {
        return sysversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbsys.sysversion
     *
     * @param sysversion the value for tbsys.sysversion
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setSysversion(String sysversion) {
        this.sysversion = sysversion;
    }
}