package abc.tzous4j.dims.model;

public class Tbusergrp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbusergrp.uid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbusergrp.ugid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer ugid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbusergrp.gid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    private Integer gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbusergrp.uid
     *
     * @return the value of tbusergrp.uid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbusergrp.uid
     *
     * @param uid the value for tbusergrp.uid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbusergrp.ugid
     *
     * @return the value of tbusergrp.ugid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getUgid() {
        return ugid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbusergrp.ugid
     *
     * @param ugid the value for tbusergrp.ugid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setUgid(Integer ugid) {
        this.ugid = ugid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbusergrp.gid
     *
     * @return the value of tbusergrp.gid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbusergrp.gid
     *
     * @param gid the value for tbusergrp.gid
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }
}