package abc.tzous4j.dims.dao;

import abc.tzous4j.dims.model.Tbdevtype;

public interface TbdevtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevtype
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevtype
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insert(Tbdevtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevtype
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insertSelective(Tbdevtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevtype
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    Tbdevtype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevtype
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKeySelective(Tbdevtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevtype
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKey(Tbdevtype record);
}