package abc.tzous4j.dims.dao;

import abc.tzous4j.dims.model.Tbdevmodel;

public interface TbdevmodelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int deleteByPrimaryKey(Integer modelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insert(Tbdevmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insertSelective(Tbdevmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    Tbdevmodel selectByPrimaryKey(Integer modelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKeySelective(Tbdevmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevmodel
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKey(Tbdevmodel record);
}