package abc.tzous4j.dims.dao;

import abc.tzous4j.dims.model.Tbdevinfo;

public interface TbdevinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevinfo
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int deleteByPrimaryKey(Integer devid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevinfo
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insert(Tbdevinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevinfo
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insertSelective(Tbdevinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevinfo
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    Tbdevinfo selectByPrimaryKey(Integer devid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevinfo
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKeySelective(Tbdevinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevinfo
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKey(Tbdevinfo record);
}