package abc.tzous4j.dims.dao;

import abc.tzous4j.dims.model.Tbdevlog;

public interface TbdevlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevlog
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevlog
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insert(Tbdevlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevlog
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insertSelective(Tbdevlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevlog
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    Tbdevlog selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevlog
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKeySelective(Tbdevlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdevlog
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKey(Tbdevlog record);
}