package abc.tzous4j.dims.dao;

import abc.tzous4j.dims.model.Tbgrp;

public interface TbgrpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbgrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insert(Tbgrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbgrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insertSelective(Tbgrp record);
}