package abc.tzous4j.dims.dao;

import abc.tzous4j.dims.model.Tbsys;

public interface TbsysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int deleteByPrimaryKey(Integer sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insert(Tbsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insertSelective(Tbsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    Tbsys selectByPrimaryKey(Integer sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKeySelective(Tbsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbsys
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKey(Tbsys record);
}