package abc.tzous4j.dims.dao;

import abc.tzous4j.dims.model.Tbusergrp;

public interface TbusergrpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusergrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusergrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insert(Tbusergrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusergrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int insertSelective(Tbusergrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusergrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    Tbusergrp selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusergrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKeySelective(Tbusergrp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbusergrp
     *
     * @mbg.generated Fri Sep 28 10:33:33 CST 2018
     */
    int updateByPrimaryKey(Tbusergrp record);
}